stages:
  - build
  - test
  - package

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  script:
    - "mvn compile"

test_job:
  stage: test
  script:
    - "mvn test"

package_job:
  stage: package
  artifacts:
    paths:
      - target/*.jar
  script:
    - "mvn package"
