# docker-compose fala sobre o container em si
version: "3.7"
services:
  # nome que eu quiser pro servidor
  webserver:
    #nome da imagem criada
    image: webservernginx
    container_name: webserver
    build:
      # usamos '.' porque vai usar o dockerfile que está na mesma pasta como referência pra criar a imagem
      context: .
    # redirecionamento de porta pra não dar conflito entre serviços diferentes
    ports:
      - "8000:80"
    # usando uma placa de rede / rede / switch criada abaixo na sessão "networks"
    networks:
      - webservereth

networks:
  webservereth:
    driver: bridge
# volumes:
#   site:
#     # -d sobe a imagem detached do terminal, pra rodar no background
#     docker-compose up -d
#     #docker-compose down exclui o container

# last docker desktop for mac broke the buildkit, a workaround is to disable it in the json config file: Docker desktop -> Settings -> Docker Engine -> Change the "features": { buildkit: true} to "features": { buildkit: false}.
